### PR TITLE
Add lumen and dingo/api support to ListProperties Command.

### PR DESCRIPTION
**Pull request by eleven26**
### Add lumen and dingo/api support to ListProperties Command.

The return value of `app('router')` in Laravel is different from Lumen, it'll return array when in Lumen, but return collection in Laravel. If you use dingo, `app('api.router')->getRoutes()` will return an array with api version as key.

### CODE REVIEW

**Comment by hhxsv5** [comment]
Thanks for your PRs. LaravelS is compatible with Laravel/Lumen 5.1+, so it will be better if your PRs keep this compatibility.

**Comment by eleven26** [comment]
> Thanks for your PRs. LaravelS is compatible with Laravel/Lumen 5.1+, so it will be better if your PRs keep this compatibility.

What do you mean? Is the code imcompatible with some versions of Laravel/Lumen 5.1+, or should I remove the compatibility for dingo ? I haven't test for lower Laravel/Lumen version yet. These code pass these in Laravel5.8 and Lumen5.5

**Comment by hhxsv5** [comment]
> > Thanks for your PRs. LaravelS is compatible with Laravel/Lumen 5.1+, so it will be better if your PRs keep this compatibility.
> 
> What do you mean? Is the code imcompatible with some versions of Laravel/Lumen 5.1+, or should I remove the compatibility for dingo ? I haven't test for lower Laravel/Lumen version yet. These code pass these in Laravel5.8 and Lumen5.5

Your PRs should be compatible with Laravel/Lumen 5.1~5.8

**Comment by hhxsv5** [comment]
[Keep compatible with 5.1-5.8](https://github.com/hhxsv5/laravel-s/commit/b3eb75899ee2b9e420393eb05309fc6eaf2ba0c6)

**Pull request closed without merging**
